name: Build

on: [pull_request]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: src/main/frontend/node_modules
          key: ${{ runner.os }}-pr-${{ env.cache-name }}-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-pr-${{ env.cache-name }}-
            ${{ runner.os }}-pr-
            ${{ runner.os }}-

      - name: Cache local maven repo
        uses: actions/cache@v2
        env:
          cache-name: cache-maven-repo
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-pr-${{ GITHUB_REF }}-${{ env.cache-name }}-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-pr-${{ GITHUB_REF }}-${{ env.cache-name }}-
            ${{ runner.os }}-pr-${{ GITHUB_REF }}-
            ${{ runner.os }}-pr-
            ${{ runner.os }}-

      - name: Build with Maven
        run: mvn install
